example.property= I AM TEST

# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://database:5432/ostock_test
spring.datasource.username = postgres
spring.datasource.password = pass